"""Shared SQLAlchemy model base classes and mixins.

All ORM models should inherit from ``UUIDBase`` to get:
  - UUID primary key (server-generated, not exposed to clients as sequential ints)
  - ``created_at`` / ``updated_at`` timestamps (timezone-aware)
  - ``deleted_at`` for soft-delete support

Why UUIDs instead of sequential integers?
  - Prevents ID enumeration attacks (attackers can't guess valid resource IDs)
  - Safe to expose in URLs and JWT payloads
  - Supports multi-region / distributed inserts without coordination
  - Consistent with the project specification
"""

import uuid

from sqlalchemy import DateTime, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base shared by all SQLAlchemy ORM models.

    Imported by ``app.core.database`` so the engine can discover all tables.
    """


class UUIDMixin:
    """Adds a server-generated UUID primary key to any ORM model.

    The UUID is generated by the database on INSERT to avoid Python-level
    UUID generation races during bulk inserts.
    """

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
    )


class TimestampMixin:
    """Adds ``created_at`` and ``updated_at`` columns (timezone-aware)."""

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[DateTime | None] = mapped_column(
        DateTime(timezone=True),
        onupdate=func.now(),
        nullable=True,
    )


class SoftDeleteMixin:
    """Adds a ``deleted_at`` nullable timestamp for soft-delete support."""

    deleted_at: Mapped[DateTime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
